### ISSUE TITLE
Similar flags are overriding each other

### ISSUE THREAD

**Issue by HellRok** [katzer/mruby-tiny-opt-parser#1]
Hi,

I noticed this bug while working with your library where if you have flags that start similarly then they'll override each other.

```
assert 'OptParser#opts with similar flags' do
  parser = OptParser.new
  parser.on(:"export-targets", :string, "linux,windows")
  parser.on(:"export-directory", :string, "./exports")
  parser.parse(['--export-directory', './releases'])

  assert_equal({
    "export-targets": "linux,windows",
    "export-directory": "./releases",
  }, parser.opts)
end
```

**Comment by HellRok** [comment]
I've figured out why it's happening, it seems this line is what's causing it:

https://github.com/katzer/mruby-tiny-opt-parser/blob/cb89bcca49d5fe64526d4912a323301322f8a860/mrblib/opt_parser.rb#L150

Basically because they start with the same letter they're getting the same "short flag". I'm not sure how you'd like to go about fixing this. My thought was to generate the short flags when they're defined with `.on` and keep a hash of them you can check. If you're happy with this approach I'm happy to do the work.

**Comment by katzer** [comment]
I am aware of that. If you like you can provide a fix for it

**Comment by HellRok** [comment]
Excellent, I'll put together a pull request soon.

**Comment by vobloeb** [comment]
It would be nice to see this fixed, although mruby has several similar libraries, some of them only work with `mruby-2.1.2`, others are too heavy (requiring `mruby-onig-regex`), so this is the only usable library right now, only this bug remains.
